apiVersion: v1
kind: Service
metadata:
  name: {{ include "secoda.fullname" . }}-frontend
  labels:
    io.kompose.service: frontend
  {{- include "secoda.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    io.kompose.service: frontend
  {{- include "secoda.selectorLabels" . | nindent 4 }}
  ports:
  - name: "5006"
    port: 5006
    targetPort: 5006