apiVersion: v1
kind: Service
metadata:
  name: {{ include "secoda.fullname" . }}-worker
  labels:
    io.kompose.service: worker
  {{- include "secoda.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    io.kompose.service: worker
  {{- include "secoda.selectorLabels" . | nindent 4 }}
  ports:
  - name: "5008"
    port: 5008
    targetPort: 5008