apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: worker
  labels:
    io.kompose.service: worker
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: worker
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
        - env:
            - name: APISERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: secodasecrets
                  key: api_secret
            - name: APISERVICE_DATABASE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: secodasecrets
                  key: api_postgres_connection_string
            - name: REDIS_URL
              value: redis://redis:6379
          name: api
          image: secoda/on-premise-api:3
          command: ["/bin/sh"]
          args:
            - -c
            - ./worker.sh
          imagePullPolicy: Always
          ports:
            - containerPort: 5008
          resources:
            limits:
              memory: 2048M
            requests:
              cpu: 200m
              memory: 1024M
      restartPolicy: Always
      imagePullSecrets:
        - name: secoda-dockerhub
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: worker
  labels:
    io.kompose.service: worker
spec:
  ports:
    - name: "5008"
      port: 5008
      targetPort: 5008
  selector:
    io.kompose.service: worker
