apiVersion: apps/v1 
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis
  labels:
    io.kompose.service: redis
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - env:
        - name: REDIS
          value: REDIS
        image: redis:latest
        command: ["redis-server"]
        name: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 2048M
          requests:
            cpu: 200m
            memory: 1024M
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: redis
  labels:
    io.kompose.service: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
