apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lb
spec:
  tls:
  - secretName: lb
  rules:
  - host: "on-premise.secoda.co" # Replace with your FQDN.
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port:
              number: 80