apiVersion: apps/v1 
kind: Deployment
metadata:
  creationTimestamp: null
  name: auth
  labels:
    io.kompose.service: auth
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: auth
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: auth
    spec:
      containers:
      - env:
        - name: KEYCLOAK_IMPORT
          value: /opt/jboss/keycloak/imports/realm-export.json
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: auth_db_addr
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: auth_db_database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: auth_db_user
        - name: DB_SCHEMA
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: auth_db_schema
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: auth_db_password
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: keycloak_admin_password
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: keycloak_admin_password
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: keycloak_user
        - name: DOPPLER_TOKEN
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: doppler_token
        image: secoda/on-premise-auth:3
        name: api
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2048M
          requests:
            cpu: 200m
            memory: 1024M
      restartPolicy: Always
      imagePullSecrets:
        - name: secoda-dockerhub
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: auth
  labels:
    io.kompose.service: auth
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: auth
status:
  loadBalancer: {}
