apiVersion: apps/v1 
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend
  labels:
    io.kompose.service: frontend
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - command: ["/bin/sh"]
        args:
        - -c
        - "doppler run -- gunicorn -w 8 --bind :5006 frontend_service.wsgi"
        env:
        - name: DOPPLER_TOKEN
          valueFrom:
            secretKeyRef:
              name: secodasecrets
              key: doppler_token
        image: secoda/on-premise-frontend:3
        name: frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
        resources:
          limits:
            memory: 2048M
          requests:
            cpu: 200m
            memory: 1024M
      restartPolicy: Always
      imagePullSecrets:
        - name: secoda-dockerhub
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: frontend
  labels:
    io.kompose.service: frontend
spec:
  type: LoadBalancer
  ports:
  - name: "5006"
    port: 5006
    targetPort: 5006
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
