apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: api
  labels:
    io.kompose.service: api
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - command: ["/bin/sh"]
          args:
            - -c
            - ./server.sh
          env:
            - name: APISERVICE_DATABASE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: secodasecrets
                  key: api_postgres_connection_string
            - name: REDIS_URL
              value: redis://redis:6379
            - name: APISERVICE_INTERNAL_BASE
              value: http://api:5007
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: secodasecrets
                  key: keycloak_secret
            - name: APISERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: secodasecrets
                  key: api_secret
            - name: KEYCLOAK_CONFIG_URL
              value: http://auth:8080/auth/realms/secoda/.well-known/openid-configuration
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: secodasecrets
                  key: public_key
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: secodasecrets
                  key: private_key
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secodasecrets
                  key: keycloak_admin_password
          image: secoda/on-premise-api:5
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 5007
          resources:
            limits:
              memory: 2048M
            requests:
              cpu: 200m
              memory: 1024M
      restartPolicy: Always
      imagePullSecrets:
        - name: secoda-dockerhub
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: api
  labels:
    io.kompose.service: api
spec:
  ports:
    - name: "5007"
      port: 5007
      targetPort: 5007
  selector:
    io.kompose.service: api
